### ISSUE TITLE
Display flex

### ISSUE THREAD

**Issue by pwoestelandt** [flexbox/codeless#1]
Hey dude !

I think the default `display: flex` [here](https://github.com/flexbox/codeless/blob/master/source/assets/stylesheets/components/_typography.scss#L2) cause undesirable effect. 

By default `typography.scss` is required in `application.scss` and broke default row behavior. 

Here an example : http://cl.ly/image/3m2y0e022i2y

**Comment by flexbox** [comment]
Thanks dude
https://github.com/flexbox/codeless/commit/8462dba5a0496098f2d2a8a60c9d7eafe6d3ae50

Fixed & release

**Comment by flexbox** [comment]
You can drop the file `typography.scss`
